### ISSUE TITLE
Installation  failure

### ISSUE THREAD

**Issue by sfiri-github** [atereshkin/wgsetup#1]
Hello atereshkin,

after testing your promising script in Debian 12, i run into following issue after executing ./wgsetup:
root@pc:~# ./wgsetup 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/./wgsetup/__main__.py", line 3, in <module>
  File "/root/./wgsetup/_bootstrap/__init__.py", line 262, in bootstrap
  File "/root/./wgsetup/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/wgsetup_a27aa77296b6985cfdf5a4a8de024563867623b24f24d588057715c4b53cd742/site-packages/wgsetup.py", line 126, in main
    i = DebianInstaller(runner=run_locally, server_address=sys.argv[1])
                                                           ~~~~~~~~^^^
IndexError: list index out of range
root@pc:~# nano /root/.shiv/wgsetup_a27aa77296b6985cfdf5a4a8de024563867623b24f24d588057715c4b53cd742/site-packages/wgsetup.py
Thanks

**Comment by atereshkin** [comment]
Sorry, it's still a work in progress. [v0.0.8](https://github.com/atereshkin/wgsetup/releases/tag/v0.0.8) shoudn't have this issue though.

**Comment by sfiri-github** [comment]
I get the "unsupported os" error now on 0.0.8 on debian 12. thanksAm 02.11.2024 um 13:38 schrieb Alexander Tereshkin ***@***.***>:﻿
Sorry, it's still a work in progress. v0.0.8 shoudn't have this issue though.

**Comment by atereshkin** [comment]
@sfiri-github Can you show me what's in `/etc/issue` on your system?

**Comment by sfiri-github** [comment]
I cant, but my /etc/debian_version is 12.7, on a vps with epyc-milan cpu kvm/qemu virtualisation and python 3.11.2. i hope this helps a bit.Am 02.11.2024 um 16:42 schrieb Alexander Tereshkin ***@***.***>:﻿
@sfiri-github Can you show me what's in /etc/issue on your system?

**Comment by atereshkin** [comment]
@sfiri-github I've updated the way it detects OS version.  Try the new release from here: https://github.com/atereshkin/wgsetup/releases/tag/v0.0.9

If still says "unsupported os", please send me the output of this command:

    lsb_release -a

**Comment by sfiri-github** [comment]
Still no luck ,unsupported. Could be that the installed "yunohost.org" addition modified the debian vanilla recognition. I can try your script on a new deb installation and afterwards the yunohost addon modification. Thank you for your support!The lsb_release -a output:No lsb modules are available Distr. id debianDescr. Debian gnu/Linux 12(bookw.)Rel. 12Codname bookwormAm 02.11.2024 um 17:22 schrieb Alexander Tereshkin ***@***.***>:﻿
@sfiri-github I've updated the way it detects OS version.  Try the new release from here: https://github.com/atereshkin/wgsetup/releases/tag/v0.0.9
If still says "unsupported os", please send me the output of this command:
lsb_release -a

**Comment by atereshkin** [comment]
@sfiri-github  That's rather weird. I'm out of ideas right now, but I've made a special release entirely without the OS check. You can try it out: https://github.com/atereshkin/wgsetup/releases/tag/v0.0.9p

**Comment by sfiri-github** [comment]
...hold the horses. I retested the 0.0.9 version and it worked like a charm this time. Sorry for the mistake i guess i did not delete the 0.0.8 version before testing 0.0.9Am 02.11.2024 um 18:24 schrieb Alexander Tereshkin ***@***.***>:﻿
@sfiri-github  That's rather weird. I'm out of ideas right now, but I've made a special release entirely without the OS check. You can try it out: https://github.com/atereshkin/wgsetup/releases/tag/v0.0.9p
